version: '3'

networks:
    netisa:
        driver: bridge

services:
    web:
        build:
            context: ./
            dockerfile: web.docker
        volumes:
            - ./elisa_data/:/var/www
        networks:
            - netisa
        ports:
            - 8088:80
        expose:
            - 80
    app:
        build:
            context: ./
            dockerfile: app.docker
        volumes:
            - ./elisa_data/:/var/www
        networks:
            - netisa
    mysql:
        image: mariadb:latest
        container_name: elisa_db
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=db"
        volumes:
            - dbdata:/var/lib/mysql
        expose:
            - 3306
        networks:
            - netisa

volumes:
    dbdata:
        driver: local
